'use client'

import { Check, Heart, RefreshCw, Sparkles, UserRound } from 'lucide-react'
import { advisors } from '@/mocks/data/advisors'
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Badge, Avatar, Input, Textarea, Select, Skeleton, EmptyState, ErrorState, MessageBubble, MessageComposer, SuggestedPrompt, Tabs, TabsList, TabsTrigger, TabsContent, AdvisorCard, RecommendationCard, PageHeader, Stack } from '@/components/ui/primitives'

export default function DesignSystemPage() {
  return <main className="mx-auto flex max-w-7xl flex-col gap-16 px-5 py-10 sm:px-8 lg:px-12">
    <PageHeader eyebrow="Internal design system" title="A calmer way to build" description="Reusable foundations for a premium personal advisory experience." action={<Badge tone="success"><Check data-icon="inline-start" /> Ready to use</Badge>} />
    <section className="flex flex-col gap-6"><div><p className="overline">Foundations</p><h2 className="heading-lg mt-2">Warm intelligence</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Background','bg-background'],['Primary','bg-primary'],['Muted','bg-muted'],['Accent','bg-accent']].map(([name, color]) => <Card key={name} className="overflow-hidden"><div className={`h-20 ${color}`} /><CardContent className="pt-4"><p className="font-medium">{name}</p><p className="caption mt-1">Semantic token</p></CardContent></Card>)}</div><div className="flex flex-col gap-3"><p className="display-md">A little more like you.</p><p className="body-lg max-w-2xl text-muted-foreground">Good advice should meet you where you are, then help you take the next small step.</p></div></section>
    <section className="flex flex-col gap-6"><div><p className="overline">Controls</p><h2 className="heading-lg mt-2">Tactile, clear, accessible</h2></div><Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><Button>Start a conversation</Button><Button variant="secondary">Secondary action</Button><Button variant="outline">Learn more</Button><Button variant="ghost">Not now</Button><Button variant="destructive">Remove</Button><Button loading>Saving</Button></CardContent></Card><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Form fields</CardTitle><CardDescription>Friendly labels and human-readable feedback.</CardDescription></CardHeader><CardContent><Stack><Input label="Your name" placeholder="Maya Chen" description="This is how your advisors will greet you." /><Textarea label="What is on your mind?" placeholder="I would like to make space for..." /><Select label="Your focus" options={[{ label: 'Choose a focus', value: '' }, { label: 'Building momentum', value: 'momentum' }, { label: 'Finding balance', value: 'balance' }]} /></Stack></CardContent></Card><Card><CardHeader><CardTitle>States</CardTitle><CardDescription>Feedback that helps people move forward.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Badge>Personal</Badge><Badge tone="success">Available</Badge><Badge tone="warning">In progress</Badge><Badge tone="info">New</Badge><Badge tone="accent">Recommended</Badge></CardContent></Card></div></section>
    <section className="flex flex-col gap-6"><div><p className="overline">Advisor language</p><h2 className="heading-lg mt-2">Distinct, never disconnected</h2></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{advisors.slice(0, 3).map((advisor) => <AdvisorCard key={advisor.id} advisor={advisor} />)}</div><RecommendationCard advisor={advisors[0]} title="A small review can clear the fog" description="Take ten minutes to look at what is working before you decide what to change." action={<Button size="sm">Take a look</Button>} /></section>
    <section className="flex flex-col gap-6"><div><p className="overline">Conversation primitives</p><h2 className="heading-lg mt-2">Personal, not mechanical</h2></div><Card className="max-w-2xl"><CardHeader><div className="flex items-center gap-3"><Avatar name={advisors[0].name} size="sm" status="online" /><div><CardTitle>{advisors[0].name}</CardTitle><CardDescription>Here when you need a thoughtful second perspective.</CardDescription></div></div></CardHeader><CardContent><div className="flex flex-col gap-3"><MessageBubble role="advisor">Let&apos;s start with what feels most important today.</MessageBubble><MessageBubble role="user">I think I need a little momentum.</MessageBubble><div className="flex flex-wrap gap-2"><SuggestedPrompt>Help me name the next step</SuggestedPrompt><SuggestedPrompt>Reflect with me</SuggestedPrompt></div><MessageComposer /></div></CardContent></Card></section>
    <section className="flex flex-col gap-6"><div><p className="overline">Loading and recovery</p><h2 className="heading-lg mt-2">Quietly supportive states</h2></div><div className="grid gap-5 md:grid-cols-3"><Card><CardContent className="flex flex-col gap-3 pt-6"><Skeleton className="size-12 rounded-full" /><Skeleton className="h-5 w-2/3" /><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-4/5" /></CardContent></Card><EmptyState icon={Heart} title="Nothing here yet" description="Your thoughtful moments will appear here as you go." action={<Button size="sm">Begin</Button>} /><ErrorState title="We hit a small pause" description="Your advisors are still here. Try refreshing this view." onRetry={() => undefined} /></div></section>
  </main>
}

