import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { advisors } from '@/mocks/data/advisors'
import { AdvisorVisual, Badge, Button, Card, PageContainer } from '@/components/ui/primitives'
import { MarketingNavbar, Footer } from '@/components/marketing/marketing-home'

export function generateStaticParams() { return advisors.map(({ id }) => ({ advisorId: id })) }
export default async function AdvisorPage({ params }: { params: Promise<{ advisorId: string }> }) { const { advisorId } = await params; const advisor = advisors.find(({ id }) => id === advisorId); if (!advisor) notFound(); return <div className="min-h-screen bg-background"><MarketingNavbar /><PageContainer className="max-w-5xl"><Link href="/advisors" className="text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-2 inline size-4" />All advisors</Link><div className="mt-8 grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="rounded-[2rem] bg-secondary p-8 sm:p-14"><AdvisorVisual advisor={advisor} size="xl" /><p className="overline mt-10">{advisor.category}</p><h1 className="display-md mt-3">{advisor.name}</h1><p className="mt-3 text-lg text-muted-foreground">{advisor.role}</p></div><Card className="p-7 sm:p-10"><Badge tone="accent">A personal perspective</Badge><p className="body-lg mt-6">{advisor.description}</p><p className="mt-5 text-sm italic text-muted-foreground">{advisor.character}</p><div className="mt-8 flex flex-wrap gap-2">{advisor.capabilities.map((capability) => <Badge key={capability}>{capability}</Badge>)}</div><Link href="/signup"><Button size="lg" className="mt-10">Meet {advisor.name.split(' ')[0]} <ArrowRight data-icon="inline-end" /></Button></Link></Card></div></PageContainer><Footer /></div> }
