'use client'

import Link from 'next/link'
import { useState, useRef } from 'react'
import { ArrowRight, ChevronLeft, ChevronRight, Menu, X, Check, Sparkles } from 'lucide-react'
import { advisors } from '@/mocks/data/advisors'
import { AdvisorCard, AdvisorVisual, Badge, Button, Card, IconButton } from '@/components/ui/primitives'
import { cn } from '@/lib/utils'

function Logo() { return <Link href="/" className="flex items-center gap-2 text-sm font-semibold tracking-tight"><span className="flex size-8 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" aria-hidden /></span><span>personal advisors</span></Link> }

function MarketingNavbar() {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-30 border-b border-border/60 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><Link href="/advisors" className="transition hover:text-foreground">Advisors</Link><Link href="/how-it-works" className="transition hover:text-foreground">How it works</Link><Link href="/pricing" className="transition hover:text-foreground">Pricing</Link></nav><div className="hidden items-center gap-3 md:flex"><Link href="/login" className="px-3 py-2 text-sm text-muted-foreground hover:text-foreground">Log in</Link><Link href="/signup"><Button size="sm">Get started <ArrowRight data-icon="inline-end" /></Button></Link></div><IconButton label={open ? 'Close menu' : 'Open menu'} className="md:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</IconButton></div>{open ? <nav className="flex flex-col gap-1 border-t border-border/60 px-5 py-4 md:hidden"><Link href="/advisors" onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm">Advisors</Link><Link href="/how-it-works" onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm">How it works</Link><Link href="/pricing" onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm">Pricing</Link><Link href="/login" onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm">Log in</Link><Link href="/signup" onClick={() => setOpen(false)} className="mt-2"><Button className="w-full">Get started</Button></Link></nav> : null}</header>
}

function AdvisorCarousel() {
  const [active, setActive] = useState(0)
  const startX = useRef<number | null>(null)
  const current = advisors[active]
  const select = (index: number) => setActive((index + advisors.length) % advisors.length)
  return <div className="relative" onPointerDown={(event) => { startX.current = event.clientX }} onPointerUp={(event) => { if (startX.current === null) return; const delta = event.clientX - startX.current; if (Math.abs(delta) > 40) select(active + (delta < 0 ? 1 : -1)); startX.current = null }} role="region" aria-roledescription="carousel" aria-label="Personal advisors" tabIndex={0} onKeyDown={(event) => { if (event.key === 'ArrowRight') select(active + 1); if (event.key === 'ArrowLeft') select(active - 1) }}>
    <div className="relative mx-auto flex min-h-[420px] max-w-xl items-center justify-center overflow-hidden rounded-[2rem] bg-secondary/70 p-6 sm:min-h-[500px] sm:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_45%,color-mix(in_oklab,var(--primary-muted)_60%,transparent),transparent_58%)]" /><div className="relative flex w-full flex-col items-center text-center"><div className="mb-6 flex items-center gap-2" aria-live="polite"><Badge tone="accent">{current.category}</Badge><span className="caption">Advisor {active + 1} of {advisors.length}</span></div><div className="relative"><div className="absolute -inset-7 rounded-full border border-primary/10" /><AdvisorVisual advisor={current} size="xl" /></div><p className="overline mt-8">{current.role}</p><h2 className="mt-2 font-display text-3xl tracking-tight sm:text-4xl">{current.name}</h2><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">{current.description}</p><div className="mt-6 flex justify-center gap-2"><IconButton label="Previous advisor" onClick={() => select(active - 1)}><ChevronLeft /></IconButton><IconButton label="Next advisor" onClick={() => select(active + 1)}><ChevronRight /></IconButton></div></div></div><div className="mt-5 flex justify-center gap-2" aria-label="Choose an advisor">{advisors.map((advisor, index) => <button key={advisor.id} onClick={() => select(index)} aria-label={`Select ${advisor.name}`} aria-current={index === active} className={cn('h-1.5 rounded-full transition-all', index === active ? 'w-8 bg-primary' : 'w-1.5 bg-border hover:bg-primary/40')} />)}</div></div>
}

function SectionIntro({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="max-w-2xl"><p className="overline">{eyebrow}</p><h2 className="display-lg mt-4 text-balance">{title}</h2>{children ? <p className="body-lg mt-5 text-muted-foreground">{children}</p> : null}</div> }

function Footer() { return <footer className="border-t border-border/70"><div className="mx-auto flex max-w-7xl flex-col gap-10 px-5 py-12 sm:px-8 lg:flex-row lg:justify-between lg:px-10"><div><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">A little more support for the life you&apos;re building.</p></div><div className="grid grid-cols-2 gap-x-16 gap-y-8 text-sm sm:grid-cols-3"><div className="flex flex-col gap-3"><p className="font-semibold">Product</p><Link href="/advisors" className="text-muted-foreground hover:text-foreground">Advisors</Link><Link href="/how-it-works" className="text-muted-foreground hover:text-foreground">How it works</Link><Link href="/pricing" className="text-muted-foreground hover:text-foreground">Pricing</Link></div><div className="flex flex-col gap-3"><p className="font-semibold">Company</p><span className="text-muted-foreground">About</span><span className="text-muted-foreground">Contact</span></div><div className="flex flex-col gap-3"><p className="font-semibold">Legal</p><span className="text-muted-foreground">Privacy</span><span className="text-muted-foreground">Terms</span></div></div></div><div className="mx-auto max-w-7xl border-t border-border/70 px-5 py-5 text-xs text-muted-foreground sm:px-8 lg:px-10">© 2026 Personal Advisors. Made for progress.</div></footer> }

export default function MarketingHome() { return <div className="min-h-screen bg-background text-foreground"><MarketingNavbar /><main><section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-18 sm:px-8 sm:pt-24 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-28"><div><p className="overline">Your personal AI advisory team</p><h1 className="display-xl mt-6 max-w-2xl text-balance">Thoughtful guidance for the life you&apos;re building.</h1><p className="body-lg mt-7 max-w-xl text-muted-foreground">Meet a team of specialized advisors who learn what matters to you, remember the context, and help you take the next right step.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/signup"><Button size="lg">Meet your advisors <ArrowRight data-icon="inline-end" /></Button></Link><a href="#how-it-works"><Button variant="outline" size="lg">How it works</Button></a></div><p className="caption mt-5">A calmer way to make progress, one conversation at a time.</p></div><AdvisorCarousel /></section>
<section className="border-y border-border/70 bg-card/40"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-28"><SectionIntro eyebrow="One team, many perspectives" title="Whatever you&apos;re working toward, there&apos;s someone in your corner.">From everyday decisions to bigger ambitions, your advisors bring focused expertise without losing sight of the whole you.</SectionIntro><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{advisors.map((advisor) => <Link href={`/advisors/${advisor.id}`} key={advisor.id}><AdvisorCard advisor={advisor} variant="compact" /></Link>)}</div></div></section>
<section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><SectionIntro eyebrow="A simple rhythm" title="Support that gets more useful over time." /><div className="mt-14 grid gap-10 border-t border-border pt-8 md:grid-cols-3">{[['01','Tell us what matters','Share what you want to improve, what you&apos;re curious about, and what progress looks like to you.'],['02','Meet your advisor','Choose the perspective that fits the moment. Your advisor brings focus, warmth, and a point of view.'],['03','Make progress together','Keep the conversation going. Your context stays with you, so each next step starts from somewhere real.']].map(([number,title,description]) => <div key={number} className="flex flex-col gap-5"><span className="font-display text-4xl text-primary/50">{number}</span><h3 className="heading-lg">{title}</h3><p className="body-md text-muted-foreground">{description}</p></div>)}</div></section>
<section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-10 lg:py-28"><div><p className="overline text-primary-foreground/60">Personal context</p><h2 className="display-lg mt-4 text-balance">You don&apos;t have to start from zero.</h2><p className="body-lg mt-6 max-w-lg text-primary-foreground/75">Your advisors keep the thread: what you&apos;re working toward, what you&apos;ve tried, what feels realistic right now. That continuity is what makes guidance feel personal.</p></div><div className="rounded-[2rem] bg-primary-foreground/10 p-5 sm:p-8"><div className="flex items-center gap-3 border-b border-primary-foreground/15 pb-5"><AdvisorVisual advisor={advisors[0]} size="md" /><div><p className="text-sm font-medium">Maya remembers</p><p className="text-xs text-primary-foreground/60">Your financial goals</p></div></div><div className="flex flex-col gap-4 py-6"><div className="rounded-2xl bg-primary-foreground/10 p-4 text-sm leading-6">You said you want more room in your monthly budget without giving up the things that make life feel good.</div><div className="ml-8 rounded-2xl bg-primary-foreground p-4 text-sm leading-6 text-foreground">Let&apos;s find one small change that creates breathing room this week.</div></div><div className="flex items-center gap-2 border-t border-primary-foreground/15 pt-5 text-xs text-primary-foreground/60"><Check className="size-4" /> Context carried forward</div></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[1fr_1.1fr] lg:items-end"><SectionIntro eyebrow="Your advisory team" title="Different expertise. One shared understanding." /><p className="max-w-md text-muted-foreground">Your advisors are designed to work together as a thoughtful constellation around your life, not a shelf of disconnected tools.</p></div><div className="mt-14 flex flex-wrap items-end justify-center gap-3 sm:gap-5">{advisors.map((advisor, index) => <div key={advisor.id} className={cn('flex flex-col items-center gap-3', index % 2 === 1 && 'mb-10')}><AdvisorVisual advisor={advisor} size={index === 2 ? 'xl' : 'lg'} /><span className="text-sm font-medium">{advisor.name.split(' ')[0]}</span><span className="caption">{advisor.category}</span></div>)}</div></section>
<section className="border-y border-border/70 bg-secondary/50"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-16 sm:px-8 lg:flex-row lg:items-center lg:justify-between lg:px-10"><div><p className="overline">Thoughtful by design</p><h2 className="heading-lg mt-3">Your personal context stays at the center.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">You choose what to share and how you use your advisors. Built with privacy-conscious product design and a respect for the details that make your life yours.</p></div><Link href="/how-it-works" className="shrink-0"><Button variant="outline">Our approach <ArrowRight data-icon="inline-end" /></Button></Link></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="rounded-[2rem] bg-accent/50 px-6 py-14 text-center sm:px-12"><p className="overline">Start where you are</p><h2 className="display-lg mx-auto mt-4 max-w-2xl text-balance">Build a team that helps you move forward.</h2><p className="mx-auto mt-5 max-w-lg text-muted-foreground">Meet the advisors and find the perspective that feels right for what&apos;s next.</p><div className="mt-8 flex justify-center gap-3"><Link href="/signup"><Button size="lg">Create your team <ArrowRight data-icon="inline-end" /></Button></Link><Link href="/advisors"><Button variant="outline" size="lg">Browse advisors</Button></Link></div></div></section></main><Footer /></div> }

export { MarketingNavbar, Footer }
