'use client'

import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode, TextareaHTMLAttributes } from 'react'
import { useState } from 'react'
import { Check, ChevronDown, Copy, MoreHorizontal, RefreshCw, Send, Sparkles, X } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { Advisor } from '@/types/domain'

export type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link'
export type ButtonSize = 'sm' | 'md' | 'lg' | 'icon'

export function Button({ className, variant = 'primary', size = 'md', loading, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: ButtonVariant; size?: ButtonSize; loading?: boolean }) {
  return <button aria-busy={loading || undefined} className={cn('inline-flex min-h-11 items-center justify-center gap-2 rounded-xl font-medium transition duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 active:scale-[.98] disabled:pointer-events-none disabled:opacity-50', { 'h-9 min-h-9 px-3 text-sm': size === 'sm', 'px-4 py-2.5 text-sm': size === 'md', 'h-13 px-6 text-base': size === 'lg', 'size-11 min-h-11 p-0': size === 'icon', 'bg-primary text-primary-foreground shadow-[0_8px_20px_-12px_hsl(var(--primary))] hover:bg-primary-hover': variant === 'primary', 'bg-secondary text-secondary-foreground hover:bg-secondary/80': variant === 'secondary', 'border border-border bg-background text-foreground hover:border-primary/40 hover:bg-muted': variant === 'outline', 'text-muted-foreground hover:bg-muted hover:text-foreground': variant === 'ghost', 'bg-destructive text-destructive-foreground hover:bg-destructive/90': variant === 'destructive', 'text-primary underline-offset-4 hover:underline': variant === 'link' }, className)} disabled={loading || props.disabled} {...props}>{loading ? <span className="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" aria-hidden /> : null}{children}</button>
}

export function IconButton({ label, children, className, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) { return <Button aria-label={label} title={label} size="icon" variant="ghost" className={className} {...props}>{children}</Button> }

export function Card({ className, interactive, selected, variant = 'default', ...props }: HTMLAttributes<HTMLDivElement> & { interactive?: boolean; selected?: boolean; variant?: 'default' | 'elevated' | 'subtle' }) { return <div className={cn('rounded-2xl border border-border bg-card text-card-foreground', variant === 'elevated' && 'shadow-[0_18px_45px_-30px_hsl(var(--foreground)/.4)]', variant === 'subtle' && 'border-transparent bg-muted/60', interactive && 'transition duration-200 hover:-translate-y-0.5 hover:border-primary/25 hover:shadow-[0_18px_45px_-30px_hsl(var(--foreground)/.4)]', selected && 'border-primary bg-primary-muted ring-1 ring-primary/20', className)} {...props} /> }
export function CardHeader({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn('flex flex-col gap-1.5 p-6', className)} {...props} /> }
export function CardTitle({ className, ...props }: HTMLAttributes<HTMLHeadingElement>) { return <h3 className={cn('font-serif text-xl leading-tight tracking-tight', className)} {...props} /> }
export function CardDescription({ className, ...props }: HTMLAttributes<HTMLParagraphElement>) { return <p className={cn('text-sm leading-6 text-muted-foreground', className)} {...props} /> }
export function CardContent({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn('px-6 pb-6', className)} {...props} /> }
export function CardFooter({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn('flex items-center gap-3 px-6 pb-6', className)} {...props} /> }

export function Badge({ className, tone = 'neutral', ...props }: HTMLAttributes<HTMLSpanElement> & { tone?: 'neutral' | 'success' | 'warning' | 'info' | 'accent' }) { return <span className={cn('inline-flex w-fit items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium', tone === 'neutral' && 'bg-muted text-muted-foreground', tone === 'success' && 'bg-success/12 text-success', tone === 'warning' && 'bg-warning/15 text-warning-foreground', tone === 'info' && 'bg-info/12 text-info-foreground', tone === 'accent' && 'bg-primary-muted text-primary', className)} {...props} /> }

export function Avatar({ src, name, size = 'md', className, accent, status }: { src?: string; name: string; size?: 'sm' | 'md' | 'lg' | 'xl'; className?: string; accent?: string; status?: 'online' | 'away' }) { return <div className={cn('relative flex shrink-0 items-center justify-center overflow-visible rounded-full bg-primary-muted font-serif text-primary', { 'size-9 text-sm': size === 'sm', 'size-12 text-base': size === 'md', 'size-16 text-xl': size === 'lg', 'size-24 text-3xl': size === 'xl' }, className)}><div className="size-full overflow-hidden rounded-full" style={accent ? { background: accent } : undefined}>{src ? <img src={src} alt={`${name} avatar`} className="size-full object-cover" /> : name.split(' ').map((word) => word[0]).slice(0, 2).join('')}</div>{status ? <span className={cn('absolute bottom-0 right-0 size-3 rounded-full border-2 border-card', status === 'online' ? 'bg-success' : 'bg-warning')} aria-label={status} /> : null}</div> }

export function Field({ label, description, error, required, children }: { label?: string; description?: string; error?: string; required?: boolean; children: ReactNode }) { return <div className="flex flex-col gap-1.5">{label ? <label className="text-sm font-medium">{label}{required ? <span className="ml-1 text-destructive" aria-hidden>*</span> : null}</label> : null}{children}{error ? <p className="text-xs text-destructive" role="alert">{error}</p> : description ? <p className="text-xs text-muted-foreground">{description}</p> : null}</div> }
export function Input({ className, label, description, error, required, ...props }: InputHTMLAttributes<HTMLInputElement> & { label?: string; description?: string; error?: string }) { return <Field label={label} description={description} error={error} required={required}><input aria-invalid={!!error} className={cn('h-11 w-full rounded-xl border border-input bg-background px-3.5 text-sm outline-none transition placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/20 disabled:cursor-not-allowed disabled:opacity-50', error && 'border-destructive', className)} {...props} /></Field> }
export function Textarea({ className, label, description, error, required, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label?: string; description?: string; error?: string }) { return <Field label={label} description={description} error={error} required={required}><textarea aria-invalid={!!error} className={cn('min-h-28 w-full resize-y rounded-xl border border-input bg-background px-3.5 py-3 text-sm outline-none transition placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/20 disabled:cursor-not-allowed disabled:opacity-50', error && 'border-destructive', className)} {...props} /></Field> }
export function Select({ label, options, value, onChange }: { label?: string; options: { label: string; value: string }[]; value?: string; onChange?: (value: string) => void }) { return <Field label={label}><div className="relative"><select value={value} onChange={(event) => onChange?.(event.target.value)} className="h-11 w-full appearance-none rounded-xl border border-input bg-background px-3.5 pr-10 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/20">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 size-4 text-muted-foreground" aria-hidden /></div></Field> }
export function Separator({ className }: { className?: string }) { return <div role="separator" className={cn('h-px w-full bg-border', className)} /> }
export function Skeleton({ className }: { className?: string }) { return <div className={cn('animate-pulse rounded-lg bg-muted', className)} aria-hidden /> }
export function EmptyState({ icon: Icon = Sparkles, title, description, action, secondaryAction }: { icon?: typeof Sparkles; title: string; description: string; action?: ReactNode; secondaryAction?: ReactNode }) { return <div className="flex flex-col items-center justify-center gap-4 rounded-2xl border border-dashed border-border bg-muted/30 px-6 py-14 text-center"><div className="flex size-12 items-center justify-center rounded-full bg-primary-muted text-primary"><Icon className="size-5" aria-hidden /></div><div className="max-w-sm"><h3 className="font-serif text-xl">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{description}</p></div>{action || secondaryAction ? <div className="flex flex-wrap justify-center gap-2">{action}{secondaryAction}</div> : null}</div> }
export function ErrorState({ title = 'Something went wrong', description = 'We could not complete that just now. Please try again.', onRetry }: { title?: string; description?: string; onRetry?: () => void }) { return <div role="alert" className="flex flex-col items-center gap-3 rounded-2xl border border-destructive/20 bg-destructive/5 px-6 py-10 text-center"><h3 className="font-serif text-xl">{title}</h3><p className="max-w-sm text-sm text-muted-foreground">{description}</p>{onRetry ? <Button variant="outline" onClick={onRetry}><RefreshCw data-icon="inline-start" /> Try again</Button> : null}</div> }

export function PageContainer({ className, children }: { className?: string; children: ReactNode }) { return <main className={cn('mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 lg:px-10 lg:py-12', className)}>{children}</main> }
export function Section({ className, children }: { className?: string; children: ReactNode }) { return <section className={cn('flex flex-col gap-6', className)}>{children}</section> }
export function SectionHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="overline">{eyebrow}</p><h2 className="mt-1 font-serif text-2xl tracking-tight sm:text-3xl">{title}</h2>{description ? <p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{description}</p> : null}</div>{action}</div> }

export function MessageBubble({ role, children, status }: { role: 'user' | 'advisor'; children: ReactNode; status?: 'sending' | 'sent' | 'error' }) { return <div className={cn('flex', role === 'user' ? 'justify-end' : 'justify-start')}><div className={cn('max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-6', role === 'user' ? 'rounded-br-md bg-primary text-primary-foreground' : 'rounded-bl-md border border-border bg-card', status === 'error' && 'border-destructive/40')}>{children}{status === 'sending' ? <span className="ml-2 inline-block size-3 animate-pulse rounded-full bg-current opacity-50" aria-label="Sending" /> : null}</div></div> }
export function TypingIndicator() { return <div className="flex items-center gap-1 rounded-2xl rounded-bl-md border border-border bg-card px-4 py-3" aria-label="Advisor is typing"><span className="size-1.5 animate-bounce rounded-full bg-muted-foreground" /><span className="size-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:100ms]" /><span className="size-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:200ms]" /></div> }
export function MessageComposer({ onSend, placeholder = 'Ask your advisor anything...' }: { onSend?: (message: string) => void; placeholder?: string }) { const [value, setValue] = useState(''); const send = () => { if (value.trim()) { onSend?.(value.trim()); setValue('') } }; return <div className="flex items-end gap-2 rounded-2xl border border-border bg-card p-2 shadow-sm"><textarea value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); send() } }} placeholder={placeholder} rows={1} aria-label="Message your advisor" className="max-h-28 min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none placeholder:text-muted-foreground" /><Button size="icon" onClick={send} aria-label="Send message"><Send className="size-4" /></Button></div> }
export function SuggestedPrompt({ children, onClick }: { children: ReactNode; onClick?: () => void }) { return <button onClick={onClick} className="rounded-full border border-border bg-card px-3 py-2 text-left text-sm text-muted-foreground transition hover:border-primary/40 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{children}</button> }

export function useDisclosure(initial = false) { const [open, setOpen] = useState(initial); return { open, onOpen: () => setOpen(true), onClose: () => setOpen(false), setOpen } }

export function Stack({ className, children }: { className?: string; children: ReactNode }) { return <div className={cn('flex flex-col gap-4', className)}>{children}</div> }
export function Inline({ className, children }: { className?: string; children: ReactNode }) { return <div className={cn('flex flex-wrap items-center gap-3', className)}>{children}</div> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="overline">{eyebrow}</p><h1 className="display-md mt-2">{title}</h1>{description ? <p className="body-md mt-3 max-w-2xl text-muted-foreground">{description}</p> : null}</div>{action}</header> }
export function Tabs({ defaultValue, children }: { defaultValue: string; children: ReactNode }) { const [value, setValue] = useState(defaultValue); return <div data-tabs-value={value}>{typeof children === 'function' ? children(value, setValue) : children}</div> }
export function TabsList({ className, children }: { className?: string; children: ReactNode }) { return <div role="tablist" className={cn('inline-flex rounded-xl bg-muted p-1', className)}>{children}</div> }
export function TabsTrigger({ value, active, onSelect, children }: { value: string; active?: boolean; onSelect?: (value: string) => void; children: ReactNode }) { return <button role="tab" aria-selected={active} onClick={() => onSelect?.(value)} className={cn('rounded-lg px-3 py-2 text-sm transition', active ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground')}>{children}</button> }
export function TabsContent({ children }: { children: ReactNode }) { return <div className="mt-4">{children}</div> }

const advisorAccent: Record<string, string> = { sage: 'advisor-sage', peach: 'advisor-peach', lavender: 'advisor-lavender', sky: 'advisor-sky', butter: 'advisor-butter', rose: 'advisor-rose' }
export function AdvisorVisual({ advisor, size = 'lg' }: { advisor: Advisor; size?: 'md' | 'lg' | 'xl' }) { return <div className={cn('relative flex shrink-0 items-center justify-center overflow-hidden rounded-[1.5rem] font-serif text-primary', advisorAccent[advisor.visual.accent] || 'advisor-sage', size === 'md' && 'size-16 text-xl', size === 'lg' && 'size-24 text-3xl', size === 'xl' && 'size-32 text-4xl')}><span aria-hidden>{advisor.visual.initials}</span></div> }
export function AdvisorCard({ advisor, variant = 'standard' }: { advisor: Advisor; variant?: 'compact' | 'standard' | 'featured' }) { return <Card interactive className={cn('overflow-hidden', variant === 'featured' && 'md:col-span-2')}><div className="flex flex-col gap-5 p-5"><div className="flex items-start justify-between gap-4"><AdvisorVisual advisor={advisor} size={variant === 'compact' ? 'md' : 'lg'} /><Badge tone={advisor.isAvailable ? 'success' : 'neutral'}>{advisor.isAvailable ? 'Available' : 'Away'}</Badge></div><div><h3 className="heading-md">{advisor.name}</h3><p className="mt-1 text-sm text-muted-foreground">{advisor.role}</p>{variant !== 'compact' ? <p className="mt-3 text-sm leading-6 text-muted-foreground">{advisor.description}</p> : null}</div>{variant !== 'compact' ? <Inline>{advisor.capabilities.slice(0, 2).map((capability) => <Badge key={capability}>{capability}</Badge>)}</Inline> : null}<Button variant={variant === 'featured' ? 'primary' : 'outline'} size="sm">Talk with {advisor.name.split(' ')[0]}</Button></div></Card> }
export function RecommendationCard({ advisor, title, description, action, timestamp }: { advisor: Advisor; title: string; description: string; action?: ReactNode; timestamp?: string }) { return <Card variant="subtle"><CardContent className="flex flex-col gap-4 pt-6 sm:flex-row sm:items-center"><AdvisorVisual advisor={advisor} size="md" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{advisor.name}</p>{timestamp ? <span className="caption">{timestamp}</span> : null}</div><h3 className="heading-md mt-1">{title}</h3><p className="body-sm mt-1 text-muted-foreground">{description}</p></div>{action}</CardContent></Card> }
